"""initial schema

Revision ID: 3b8cdbea68d6
Revises: 
Create Date: 2026-03-17 00:12:01.254863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '3b8cdbea68d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Старые схемы/ручные БД могли не иметь ожидаемых имён unique/index — не падаем на DROP.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_members', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=False)
    op.execute(
        text(
            "ALTER TABLE chat_members "
            "DROP CONSTRAINT IF EXISTS chat_members_chat_id_user_id_key"
        )
    )
    op.execute(text("DROP INDEX IF EXISTS idx_chat_members_chat_id"))
    op.execute(text("DROP INDEX IF EXISTS idx_chat_members_user_id"))
    op.create_index(op.f('ix_chat_members_id'), 'chat_members', ['id'], unique=False, if_not_exists=True)
    # Старые БД могли оставить одноимённый unique-index без строки в pg_constraint —
    # тогда IF по pg_constraint даёт false, а ADD CONSTRAINT падает с "relation already exists".
    op.execute(
        text(
            "ALTER TABLE chat_members DROP CONSTRAINT IF EXISTS uq_chat_members_chat_user"
        )
    )
    op.execute(text("DROP INDEX IF EXISTS uq_chat_members_chat_user"))
    op.execute(
        text(
            """
            DO $body$
            BEGIN
              IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint c
                JOIN pg_class t ON c.conrelid = t.oid
                WHERE t.relname = 'chat_members'
                  AND c.conname = 'uq_chat_members_chat_user'
              ) THEN
                ALTER TABLE chat_members
                ADD CONSTRAINT uq_chat_members_chat_user
                UNIQUE (chat_id, user_id);
              END IF;
            END
            $body$ LANGUAGE plpgsql
            """
        )
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False, if_not_exists=True)
    op.alter_column('messages', 'is_updated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.execute(text("DROP INDEX IF EXISTS idx_messages_chat_id"))
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index(op.f('idx_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.alter_column('messages', 'is_updated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_constraint('uq_chat_members_chat_user', 'chat_members', type_='unique')
    op.drop_index(op.f('ix_chat_members_id'), table_name='chat_members')
    op.create_index(op.f('idx_chat_members_user_id'), 'chat_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_chat_members_chat_id'), 'chat_members', ['chat_id'], unique=False)
    op.create_unique_constraint(op.f('chat_members_chat_id_user_id_key'), 'chat_members', ['chat_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('chat_members', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'member'::character varying"),
               nullable=True)
    # ### end Alembic commands ###
