// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyTmLUZz6XvjIr3QH5mbKZBfz6qr1MFME',
    appId: '1:1097681972848:web:d80c43729e2da26eabceb5',
    messagingSenderId: '1097681972848',
    projectId: 'chtp-chat',
    authDomain: 'chtp-chat.firebaseapp.com',
    storageBucket: 'chtp-chat.firebasestorage.app',
    measurementId: 'G-9E3L8WTDSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd_uJKYOpIxzMwRZT_K78wfh49xxCQCmE',
    appId: '1:1097681972848:android:8a760ec33bfd4743abceb5',
    messagingSenderId: '1097681972848',
    projectId: 'chtp-chat',
    storageBucket: 'chtp-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLADVGym2b0Cc2JxAg8Y-UXSbBoC9Wsac',
    appId: '1:1097681972848:ios:cfc0e0c418f982f3abceb5',
    messagingSenderId: '1097681972848',
    projectId: 'chtp-chat',
    storageBucket: 'chtp-chat.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLADVGym2b0Cc2JxAg8Y-UXSbBoC9Wsac',
    appId: '1:1097681972848:ios:cfc0e0c418f982f3abceb5',
    messagingSenderId: '1097681972848',
    projectId: 'chtp-chat',
    storageBucket: 'chtp-chat.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyTmLUZz6XvjIr3QH5mbKZBfz6qr1MFME',
    appId: '1:1097681972848:web:0fc849c898b67b69abceb5',
    messagingSenderId: '1097681972848',
    projectId: 'chtp-chat',
    authDomain: 'chtp-chat.firebaseapp.com',
    storageBucket: 'chtp-chat.firebasestorage.app',
    measurementId: 'G-J5Y6N7B0K6',
  );
}
